# Generated by Django 4.2.11 on 2026-02-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_blockchip_id'),
        ('accounts', '0003_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteam',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.season'),
        ),
        migrations.AlterField(
            model_name='usersteam',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='usersteam',
            unique_together={('season', 'name')},
        ),
    ]
