# Generated by Django 4.2.11 on 2026-09-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_add_is_cancelled_to_grandprix'),
        ('accounts', '0005_userprofile_featured_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='abandoned_from_gp',
            field=models.ForeignKey(blank=True, help_text='First GP the participant quit at. From this round on they are out of the standings and pay no penalties; leave empty for someone who merely forgot.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.grandprix'),
        ),
    ]
