# Generated by Django 4.2.11 on 2024-08-13 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('photo_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'drivers',
                'db_table': 'public_drivers',
            },
        ),
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('nround', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(default='DEFAULT', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
                ('gp_end_date', models.DateTimeField(blank=True, null=True)),
                ('photo_link', models.CharField(blank=True, max_length=300, null=True)),
                ('country_link', models.CharField(blank=True, max_length=300, null=True)),
                ('gp_photo', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'grandPrixes',
                'db_table': 'public_grandprixes',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('color_rgb', models.CharField(blank=True, max_length=7, null=True)),
                ('photo_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'teams',
                'db_table': 'public_teams',
            },
        ),
        migrations.CreateModel(
            name='TeamPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('gp', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='public.grandprix')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.team')),
            ],
            options={
                'verbose_name_plural': 'teampoints',
                'db_table': 'public_teampoints',
            },
        ),
        migrations.CreateModel(
            name='RaceResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_lap_res', to='public.driver')),
                ('first_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_pos_res', to='public.driver')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.grandprix')),
                ('poleman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poleman_res', to='public.driver')),
                ('second_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_pos_res', to='public.driver')),
                ('team_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_winner_res', to='public.team')),
                ('third_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_pos_res', to='public.driver')),
            ],
            options={
                'verbose_name_plural': 'raceresults',
                'db_table': 'public_raceresults',
            },
        ),
        migrations.CreateModel(
            name='Porra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_date', models.DateTimeField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('driver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver1', to='public.driver')),
                ('driver2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver2', to='public.driver')),
                ('driver3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver3', to='public.driver')),
                ('driver4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver4', to='public.driver')),
                ('driver5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver5', to='public.driver')),
                ('fast_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_lap', to='public.driver')),
                ('first_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_pos', to='public.driver')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.grandprix')),
                ('poleman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poleman', to='public.driver')),
                ('second_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_pos', to='public.driver')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='public.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='public.team')),
                ('team_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_winner', to='public.team')),
                ('third_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_pos', to='public.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'porras',
                'db_table': 'public_porra',
            },
        ),
        migrations.CreateModel(
            name='DriverPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.driver')),
                ('gp', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='public.grandprix')),
            ],
            options={
                'verbose_name_plural': 'driverpoints',
                'db_table': 'public_driverpoints',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.team'),
        ),
    ]
