# Generated by Django 4.2.11 on 2025-03-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='selected_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='selected_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
