# Generated by Django 4.2.11 on 2026-02-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_porra_tirple_block_chips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
