# Generated by Django 4.2.11 on 2025-03-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_fill_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverpoints',
            name='driver_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverpoints_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='driverpoints',
            name='gp_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverpoints_new', to='public.grandprix', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='porra',
            name='driver1_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver1_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='driver2_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver2_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='driver3_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver3_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='driver4_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver4_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='driver5_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver5_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='fast_lap_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_lap_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='first_pos_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_pos_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='gp_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='porra_new', to='public.grandprix', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='poleman_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poleman_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='second_pos_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_pos_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='team1_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_new', to='public.team', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='team2_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_new', to='public.team', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='team_winner_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_winner_new', to='public.team', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='porra',
            name='third_pos_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_pos_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='raceresults',
            name='fast_lap_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_lap_res_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='raceresults',
            name='first_pos_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_pos_res_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='raceresults',
            name='gp_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raceresults_new', to='public.grandprix', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='raceresults',
            name='poleman_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poleman_res_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='raceresults',
            name='second_pos_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_pos_res_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='raceresults',
            name='team_winner_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_winner_res_new', to='public.team', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='raceresults',
            name='third_pos_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_pos_res_new', to='public.driver', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='team',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teampoints',
            name='gp_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teampoints_new', to='public.grandprix', to_field='temp_id'),
        ),
        migrations.AddField(
            model_name='teampoints',
            name='team_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teampoints_new', to='public.team', to_field='temp_id'),
        ),
        migrations.AlterField(
            model_name='driverpoints',
            name='driver',
            field=models.ForeignKey(db_column='driver', on_delete=django.db.models.deletion.CASCADE, to='public.driver'),
        ),
        migrations.AlterField(
            model_name='grandprix',
            name='country',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raceresults',
            name='team_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_winner_res', to='public.team', to_field='temp_id'),
        ),
        migrations.AlterField(
            model_name='teampoints',
            name='team',
            field=models.ForeignKey(db_column='team', on_delete=django.db.models.deletion.CASCADE, to='public.team'),
        ),
    ]
