# Generated by Django 4.2.11 on 2026-02-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
