# Generated by Django 4.2.11 on 2026-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_achievement_id_alter_userachievement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grandprix',
            old_name='gp_end_date',
            new_name='gp_date',
        ),
        migrations.AddField(
            model_name='grandprix',
            name='qualy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
