# Generated by Django 4.2.11 on 2026-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_rename_gp_end_date_grandprix_gp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandprix',
            name='is_sprint',
            field=models.BooleanField(default=False),
        ),
    ]
