# Generated by Django 4.2.11 on 2026-03-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_add_is_sprint_to_grandprix'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGPPointsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualy_driver_pts_sum', models.IntegerField(default=0, help_text="Sum of both drivers' qualy points")),
                ('qualy_team_bonus', models.IntegerField(default=0, help_text='Team qualy bonus (1/3/5)')),
                ('qualy_total', models.IntegerField(default=0, help_text='Sum of team qualy components')),
                ('race_driver_pts_sum', models.IntegerField(default=0, help_text="Sum of both drivers' race points")),
                ('race_total', models.IntegerField(default=0, help_text='Team race total')),
                ('sprint_driver_pts_sum', models.IntegerField(default=0, help_text='Sum of sprint points')),
                ('sprint_total', models.IntegerField(default=0, help_text='Team sprint total')),
                ('auto_total', models.IntegerField(default=0, help_text='Automatic total (qualy + race + sprint)')),
                ('admin_adjustment', models.IntegerField(default=0, help_text='Manual adjustment by admin')),
                ('final_total', models.IntegerField(default=0, help_text='auto_total + admin_adjustment')),
                ('admin_note', models.TextField(blank=True, default='', help_text='Explanation for admin adjustment')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.grandprix')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.team')),
            ],
            options={
                'verbose_name_plural': 'team GP points detail',
                'db_table': 'public_teamgppointsdetail',
            },
        ),
        migrations.CreateModel(
            name='DriverGPPointsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualy_participation', models.IntegerField(default=0, help_text='1=Q1, 2=Q2, 3=Q3')),
                ('qualy_position', models.IntegerField(default=0, help_text='Reverse-grid points (0-10)')),
                ('qualy_teammate', models.IntegerField(default=0, help_text='Teammate bonus (0 or 1)')),
                ('qualy_dns_penalty', models.IntegerField(default=0, help_text='-10 if no Q1 time set')),
                ('qualy_total', models.IntegerField(default=0, help_text='Sum of qualy components')),
                ('race_f1_points', models.IntegerField(default=0, help_text='F1 position points (25,18,...)')),
                ('race_positions_gained', models.IntegerField(default=0, help_text='Positions gained/lost')),
                ('race_teammate', models.IntegerField(default=0, help_text='Teammate bonus (0 or 2)')),
                ('race_dnf_penalty', models.IntegerField(default=0, help_text='-10 if DNF')),
                ('race_total', models.IntegerField(default=0, help_text='Sum of race components')),
                ('sprint_position_pts', models.IntegerField(default=0, help_text='Sprint position points (8,7,...)')),
                ('sprint_positions_gained', models.IntegerField(default=0, help_text='Sprint positions gained')),
                ('sprint_teammate', models.IntegerField(default=0, help_text='Sprint teammate bonus (0 or 2)')),
                ('sprint_dnf_penalty', models.IntegerField(default=0, help_text='-10 if sprint DNF')),
                ('sprint_total', models.IntegerField(default=0, help_text='Sum of sprint components')),
                ('auto_total', models.IntegerField(default=0, help_text='Automatic total (qualy + race + sprint)')),
                ('admin_adjustment', models.IntegerField(default=0, help_text='Manual adjustment by admin')),
                ('final_total', models.IntegerField(default=0, help_text='auto_total + admin_adjustment')),
                ('admin_note', models.TextField(blank=True, default='', help_text='Explanation for admin adjustment')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.driver')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.grandprix')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.season')),
            ],
            options={
                'verbose_name_plural': 'driver GP points detail',
                'db_table': 'public_drivergppointsdetail',
            },
        ),
        migrations.AddConstraint(
            model_name='teamgppointsdetail',
            constraint=models.UniqueConstraint(fields=('season', 'team', 'gp'), name='unique_team_gp_detail'),
        ),
        migrations.AddConstraint(
            model_name='drivergppointsdetail',
            constraint=models.UniqueConstraint(fields=('season', 'driver', 'gp'), name='unique_driver_gp_detail'),
        ),
    ]
