# Generated by Django 4.2.11 on 2026-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_add_driver_team_gp_points_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivergppointsdetail',
            name='sprint_qualy_dns_penalty',
            field=models.IntegerField(default=0, help_text='-10 if sprint qualy DNS'),
        ),
        migrations.AddField(
            model_name='drivergppointsdetail',
            name='sprint_qualy_participation',
            field=models.IntegerField(default=0, help_text='1=SQ1, 2=SQ2, 3=SQ3'),
        ),
        migrations.AddField(
            model_name='drivergppointsdetail',
            name='sprint_qualy_position',
            field=models.IntegerField(default=0, help_text='Reverse-grid points from sprint qualy'),
        ),
        migrations.AddField(
            model_name='drivergppointsdetail',
            name='sprint_qualy_teammate',
            field=models.IntegerField(default=0, help_text='Sprint qualy teammate bonus (0 or 1)'),
        ),
        migrations.AddField(
            model_name='drivergppointsdetail',
            name='sprint_qualy_total',
            field=models.IntegerField(default=0, help_text='Sum of sprint qualy components'),
        ),
        migrations.AddField(
            model_name='teamgppointsdetail',
            name='sprint_qualy_driver_pts_sum',
            field=models.IntegerField(default=0, help_text='Sum of sprint qualy points'),
        ),
        migrations.AddField(
            model_name='teamgppointsdetail',
            name='sprint_qualy_team_bonus',
            field=models.IntegerField(default=0, help_text='Sprint qualy team bonus (1/3/5)'),
        ),
        migrations.AddField(
            model_name='teamgppointsdetail',
            name='sprint_qualy_total',
            field=models.IntegerField(default=0, help_text='Team sprint qualy total'),
        ),
        migrations.AlterField(
            model_name='drivergppointsdetail',
            name='auto_total',
            field=models.IntegerField(default=0, help_text='Automatic total (qualy + race + sprint qualy + sprint race)'),
        ),
        migrations.AlterField(
            model_name='drivergppointsdetail',
            name='sprint_total',
            field=models.IntegerField(default=0, help_text='Sum of sprint race components'),
        ),
        migrations.AlterField(
            model_name='teamgppointsdetail',
            name='sprint_driver_pts_sum',
            field=models.IntegerField(default=0, help_text='Sum of sprint race points'),
        ),
        migrations.AlterField(
            model_name='teamgppointsdetail',
            name='sprint_total',
            field=models.IntegerField(default=0, help_text='Team sprint race total'),
        ),
    ]
