# Generated by Django 4.2.11 on 2026-05-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_add_sprint_qualy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandprix',
            name='api_round',
            field=models.PositiveIntegerField(blank=True, help_text='Round number used by external APIs (Jolpica/OpenF1). Defaults to nround if not set.', null=True),
        ),
    ]
