# Generated by Django 4.2.11 on 2026-09-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_add_api_round_to_grandprix'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandprix',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Race dropped from the calendar; kept to preserve the original round numbering.'),
        ),
    ]
